events { worker_connections 1024; }

http {
  upstream auth     { server auth-service:3001; }
  upstream products { server product-service:3002; }
  upstream orders   { server order-service:3003; }
  upstream anomaly  { server anomaly-detector:3004; }

  server {
    listen 80;

    location = /health {
      return 200 '{"gateway":"ok"}';
      add_header Content-Type application/json;
    }

    location /auth/ {
      proxy_pass         http://auth/;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
    }

    location /products/ {
      proxy_pass         http://products/;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
    }

    location /orders/ {
      proxy_pass         http://orders/;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
    }

    location /incidents/ {
      proxy_pass         http://anomaly/;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
    }
  }
}
